language: node_js
node_js:
  - "8"

addons:
  apt:
    update: true

cache:
  directories:
    - dist/assets

before_script:
  - sudo apt-get install -y jq

script:
  - npm run build
  - git submodule init && git submodule update && cp config.js schedule-json-generator/ && cd schedule-json-generator/ && yarn && node index.js > ../dist/programs.json

deploy:
  provider: pages
  local-dir: dist/
  skip-cleanup: true
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: api2019.coscup.org
  on:
    branch:
      - master
      - deploy
